package com.tutpro.baresip

import androidx.compose.ui.graphics.Color

// App's color palette is defined by these values, which are used to build
// the MaterialTheme in AppTheme.kt

val light_primary = Color(0xff0ca1fd)
val light_on_primary = Color(0xFFFFFFFF)
val light_primary_container = Color(0xFFA1CBE6)
val light_on_primary_container = Color(0xFF032133)
val light_secondary = Color(0xFF00B9A1)
val light_on_secondary = Color(0xffe0e0e0)
val light_secondary_container = Color(0xFF9DE6DC)
val light_on_secondary_container = Color(0xFF00332C)
val light_tertiary = Color(0xFF9885B5)
val light_on_tertiary = Color(0xffe0e0e0)
val light_tertiary_container = Color(0xFFDAD2E6)
val light_on_tertiary_container = Color(0xFF2B2533)
val light_error = Color(0xFFB3261E)
val light_on_error = Color(0xffe0e0e0)
val light_error_container = Color(0xFFE6BFB1)
val light_on_error_container = Color(0xFF33180E)
val light_background = Color(0xFFFCFCFC)
val light_on_background = Color(0xFF313233)
val light_surface = Color(0xFFfbfcfc)
val light_on_surface = Color(0xFF313233)
val light_surfaceVariant = Color(0xFFd8e0e6)
val light_on_surfaceVariant = Color(0xFF535f66)
val light_outline = Color(0xFF7c8e99)

val dark_primary = Color(0xFF84C1E6)
val dark_on_primary = Color(0xFF04314C)
val dark_primary_container = Color(0xFF054166)
val dark_on_primary_container = Color(0xFFA1CBE6)
val dark_secondary = Color(0xFF7FE6D8)
val dark_on_secondary = Color(0xFF004C43)
val dark_secondary_container = Color(0xFF006659)
val dark_on_secondary_container = Color(0xFF9DE6DC)
val dark_tertiary = Color(0xFFD5CAE6)
val dark_on_tertiary = Color(0xFF40384C)
val dark_tertiary_container = Color(0xFF564A66)
val dark_on_tertiary_container = Color(0xFFDAD2E6)
val dark_error = Color(0xFFE6AF9C)
val dark_on_error = Color(0xFF4C2415)
val dark_error_container = Color(0xFF66301D)
val dark_on_error_container = Color(0xFFE6BFB1)
val dark_background = Color(0xFF313233)
val dark_on_background = Color(0xFFe2e4e6)
val dark_surface = Color(0xFF313233)
val dark_on_surface = Color(0xFFe2e4e6)
val dark_surfaceVariant = Color(0xFF535f66)
val dark_on_surfaceVariant = Color(0xFFd2dee6)
val dark_outline = Color(0xFF9daab3)
