package com.tutpro.baresip.plus

const val TAG = "Baresip"

const val BACKUP_PERMISSION_REQUEST_CODE = 1
const val RESTORE_PERMISSION_REQUEST_CODE = 2
const val RECORD_PERMISSION_REQUEST_CODE = 3
const val CONTACTS_PERMISSION_REQUEST_CODE = 4
const val CAMERA_PERMISSION_REQUEST_CODE = 5
